version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=name_database
      - MYSQL_ROOT_PASSWORD=password_database
      - MYSQL_USER=user_database
    networks:
      - node-network
networks:
  node-network:
    driver: bridge